### PR TITLE
Update Models/Shapes.java

### PR DESCRIPTION
**Pull request by vishaal27**
According to what I have gathered, I've made the required changes. Please check if its changed correctly.

### CODE REVIEW

**Comment by yoavst** [comment]
It doesn't compile...

**Comment by vishaal27** [comment]
What is the error?

**Comment by yoavst** [comment]
You should also modify https://github.com/DCruz22/prj-cursobasico-10/blob/a2a2dede33530c67ea90fc22b9a331de207fc91a/app/src/main/java/app/simonsays/com/simonsays_app/activities/GameActivity.java#L30

**Comment by vishaal27** [comment]
Oh yes, completely forgot about that. Will have to create an object of the Shape class and do a couple of other changes in the GameActivity. Will do it!

**Pull request closed without merging**
